packages:
  - frontend
  - backend
  - packages/*

allowBuilds:
  argon2: true
  better-sqlite3: false
  esbuild: true
  node-llama-cpp: false
  sharp: true
  tree-sitter-go: false
  tree-sitter-javascript: false
  tree-sitter-python: false
  tree-sitter-rust: false
  tree-sitter-typescript: false
  unrs-resolver: true

overrides:
  postcss: 8.5.19
